1

In [1]:
import numpy as np

array = np.array([1, 2, 3, 4, 5], dtype=int)

print("Array'in boyutu:", array.shape)
print("Array'in eleman sayısı:", array.size)


Array'in boyutu: (5,)
Array'in eleman sayısı: 5


In [2]:
array_reshaped = array.reshape(1, 5)
print("Yeniden şekillendirilmiş array boyutu:", array_reshaped.shape)

Yeniden şekillendirilmiş array boyutu: (1, 5)


2

In [4]:
import numpy as np

array_2d = np.array([[1, 2, 6, 7], [4, 3, 9, 5]])
array_3d = np.array([[[7, 5, 14], [21, 8, 11]], [[8, 6, 20], [14, 3, 9]]])

print("İki boyutlu array boyutu:", array_2d.shape)
print("İki boyutlu array eleman sayısı:", array_2d.size)
print("İki boyutlu array satır sayısı:", array_2d.shape[0])
print("İki boyutlu array sütun sayısı:", array_2d.shape[1])

print("\nÜç boyutlu array boyutu:", array_3d.shape)
print("Üç boyutlu array eleman sayısı:", array_3d.size)
print("Üç boyutlu array ilk boyut:", array_3d.shape[0])
print("Üç boyutlu array ikinci boyut:", array_3d.shape[1])
print("Üç boyutlu array üçüncü boyut:", array_3d.shape[2])


İki boyutlu array boyutu: (2, 4)
İki boyutlu array eleman sayısı: 8
İki boyutlu array satır sayısı: 2
İki boyutlu array sütun sayısı: 4

Üç boyutlu array boyutu: (2, 2, 3)
Üç boyutlu array eleman sayısı: 12
Üç boyutlu array ilk boyut: 2
Üç boyutlu array ikinci boyut: 2
Üç boyutlu array üçüncü boyut: 3


3

In [5]:
import numpy as np

array_2d = np.array([[1, 2, 6, 7], [4, 3, 9, 5]])
array_3d = np.array([[[7, 5, 14], [21, 8, 11]], [[8, 6, 20], [14, 3, 9]]])

print("İki boyutlu array'deki 2 elemanı:", array_2d[0, 1])
print("İki boyutlu array'deki 7 elemanı:", array_2d[0, 3])
print("Üç boyutlu array'deki 9 elemanı:", array_3d[1, 1, 2])
print("Üç boyutlu array'deki 5 elemanı:", array_3d[0, 0, 1])


İki boyutlu array'deki 2 elemanı: 2
İki boyutlu array'deki 7 elemanı: 7
Üç boyutlu array'deki 9 elemanı: 9
Üç boyutlu array'deki 5 elemanı: 5


4

In [6]:
import numpy as np

array_2d = np.array([[1, 2, 6, 7], [4, 3, 9, 5]])
array_3d = np.array([[[7, 5, 14], [21, 8, 11]], [[8, 6, 20], [14, 3, 9]]])

print("İki boyutlu array'deki 2 ve 6 elemanları:", array_2d[0, 1:3])
print("İki boyutlu array'deki 3, 9, 5 elemanları:", array_2d[1, 1:4])
print("Üç boyutlu array'deki 21, 8, 11 elemanları:", array_3d[0, 1, :])
print("Üç boyutlu array'deki 6, 20 elemanları:", array_3d[1, 0, :2])


İki boyutlu array'deki 2 ve 6 elemanları: [2 6]
İki boyutlu array'deki 3, 9, 5 elemanları: [3 9 5]
Üç boyutlu array'deki 21, 8, 11 elemanları: [21  8 11]
Üç boyutlu array'deki 6, 20 elemanları: [8 6]


5

In [8]:
import numpy as np

array_zeros = np.zeros((5, 3), dtype=int)
array_ones = np.ones((5, 3), dtype=int)

array_concat_rows = np.vstack((array_zeros, array_ones))
array_concat_cols = np.hstack((array_zeros, array_ones))

print("Satır bazında birleştirilmiş array:\n", array_concat_rows)
print("\nSütun bazında birleştirilmiş array:\n", array_concat_cols)


Satır bazında birleştirilmiş array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

Sütun bazında birleştirilmiş array:
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
